version: "3.6"

services:
  rstudio:
    image: rocker/tidyverse:latest
    container_name: rstudio
    restart: on-failure
    volumes:
      - rstudio:/home/rstudio
      - r_libs:/usr/local/lib/R
    networks:
      - tki-net
    environment:
      - PASSWORD=rstudio1
      - ROOT=TRUE
    ports:
      - 8787:8787

networks:
  tki-net:
    name: net

volumes:
  r_libs:
  rstudio: